add: add numeric ID generation
ocluse/liquidsnow-cryptography pull request #2
Opened 2023-07-23 17:53 UTC by Phystro

@thismaker check it out

2023-07-23 17:58 UTC, Phystro commented on src/Cryptography/CryptoUtility.cs
I'm assuming that the line I added is appropriate - it looks appropriate

2023-07-23 17:58 UTC, Phystro reviewed
check this too

2023-07-23 18:09 UTC, thismaker commented
There are a few problems:
1. The signature of the function is `Random(Int)` but there is already another method with a similar signature i.e `Random(Int,bool)`. The second method has an optional bool, so therefore calling `string s = CryptoUtility.Random(6)` would cause some ambiguity as to which overload is being referred to.
2. The documentation is not clear, "a random numeric string" sounds better than "a random string of numbers"
3. There was no need to directly call `_random.Next`, there is already a function `Random(int min, int max)` included in the class, I'd prefer you call that function unless you have a better reason not to?

2023-07-23 18:13 UTC, thismaker requested changes

2023-07-23 18:13 UTC, thismaker commented on src/Cryptography/CryptoUtility.cs
> +            return _random.Next(min, max).ToString(CultureInfo.InvariantCulture);
you can use the preexisting function  instead, see comment for details

2023-07-23 18:13 UTC, thismaker commented on src/Cryptography/CryptoUtility.cs
> +        /// Generates a random string of numbers of specified <paramref name="length"/>
Prefer: random numeric string

2023-07-23 18:13 UTC, thismaker commented on src/Cryptography/CryptoUtility.cs
> +        public static string Random(int length)
Name might cause ambiguity

2023-07-23 18:38 UTC, Phystro commented
> There are a few problems:
> 
> 1. The signature of the function is `Random(Int)` but there is already another method with a similar signature i.e `Random(Int,bool)`. The second method has an optional bool, so therefore calling `string s = CryptoUtility.Random(6)` would cause some ambiguity as to which overload is being referred to.
> 2. The documentation is not clear, "a random numeric string" sounds better than "a random string of numbers"
> 3. There was no need to directly call `_random.Next`, there is already a function `Random(int min, int max)` included in the class, I'd prefer you call that function unless you have a better reason not to?

working on them

2023-07-23 18:47 UTC, Phystro reviewed
@thismaker Corrections have been made

2023-07-23 22:16 UTC, thismaker commented
great, now bump the package version all the csprojs then you can merge

2023-07-24 04:42 UTC, Phystro reviewed
version updated to 0.0.3

2023-07-24 04:43 UTC, merged